$(document).ready(function(){
    $("#menu").click(function(){
        $(".menu").toggleClass("close");
        $(".n_c").toggleClass("close");
        $(".sec1").toggleClass("close");
        $(".sec2").toggleClass("close");
        $(".sec3").toggleClass("close");
    })
})